name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    strategy:
      matrix:
        node-version: [12.18.3]
        os: [windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          path: "**/node_modules"
      - run: npm ci
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build
