name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    strategy:
      matrix:
        node-version: [12.18.3]
        os: [windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          path: "**/node_modules"
      - run: npm ci
      - run: npx cross-env NODE_ENV=production npm run build
      - run: npx electron-builder --ia32 --win
      - run: npx ts-node scripts/create-zip-for-github-release.ts
      - env:
          GIT_AUTHOR_EMAIL: 73190177+metaneno@users.noreply.github.com
          GIT_AUTHOR_NAME: metaneno
          GIT_COMMITTER_EMAIL: 73190177+metaneno@users.noreply.github.com
          GIT_COMMITTER_NAME: metaneno
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
